layout: created BaseInput
bacebu4/sr-web pull request #2
Opened 2021-02-20 20:41 UTC by vlad99902

Created new component. Team lead lord, please merge it.

2021-02-21 03:30 UTC, bacebu4 requested changes

2021-02-21 03:30 UTC, bacebu4 commented on src/components/BaseInput.tsx
> +import React, { InputHTMLAttributes } from "react";
Unnecessary `React` import

2021-02-21 03:30 UTC, bacebu4 commented on src/components/BaseInput.tsx
> +  margin: ${(props) => props.margin};
In this project we're using `mt` and `ml`
For me it's easier to read
Even though this solution is more flexible let's stick to `mt` and `ml`

2021-02-21 03:30 UTC, bacebu4 commented on src/components/BaseInput.tsx
> +  border: 1px solid ${GRAY}03;
`1A` and `03` looks like a _magic_ to me
Probably don't need to hard code them
I'll add the issue about that, don't need to fix it for you

2021-02-21 03:30 UTC, bacebu4 commented on src/components/BaseInput.tsx
> +  outline: none;
Don't use it. We're making our site accessible :)

2021-02-21 03:45 UTC, bacebu4 commented on src/components/BaseInput.tsx
> +  outline: none;
I mean don't use `outline: none`

2021-02-21 03:46 UTC, bacebu4 commented on src/components/BaseInput.tsx
> +import React, { InputHTMLAttributes } from "react";
```suggestion
import { InputHTMLAttributes } from "react";
```

2021-02-21 03:46 UTC, bacebu4 commented on src/components/BaseInput.tsx
> +  outline: none;
```suggestion
```

2021-02-21 04:10 UTC, bacebu4 commented on src/components/BaseInput.tsx
> +  border-radius: 9px;
```suggestion
  border-radius: 14px;
```

2021-02-21 04:10 UTC, bacebu4 commented on src/components/BaseInput.tsx
> +  border-radius: 9px;
To match changed design

2021-02-21 04:58 UTC, bacebu4 commented on src/components/BaseInput.tsx
> +  font-size: 1rem;
```suggestion
  font-size: 0.875rem;
```

2021-02-21 04:59 UTC, bacebu4 commented
ALSO add color variants according to new design

2021-02-21 08:27 UTC, bacebu4 commented
And don't forget to change margins
It's all what's left

2021-02-21 18:26 UTC, vlad99902 commented
I'll fix it. :)

2021-02-23 07:09 UTC, bacebu4 approved these changes

2021-02-23 07:11 UTC, closed without merging

2021-02-23 07:11 UTC, bacebu4 commented
Went all wrong!